[target.riscv32i-unknown-none-elf]
runner = "riscv64-unknown-elf-gdb -q -x gdb_init"
rustflags = [
   "-C", "link-arg=-Tmemory.x",
   
]

[build]
target = "riscv32i-unknown-none-elf"

[profile.dev]
opt-level = "s"               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.
lto = "fat"